/* EnamelCraft i18n — lightweight client-side language switcher (dropdown).
   Mark translatable text with data-i18n="key"; add entries to DICT below.
   LANGS controls the dropdown menu; add/remove a language in one place. */
(function () {
  var LANGS = [
    { code: 'en', name: 'English' },
    { code: 'zh', name: '中文' },
    { code: 'es', name: 'Español' },
    { code: 'fr', name: 'Français' },
    { code: 'de', name: 'Deutsch' }
  ];
  var LANG_CODES = LANGS.map(function (l) { return l.code; });
  var LANG_MAP = {};
  LANGS.forEach(function (l) { LANG_MAP[l.code] = l; });
  // HTML lang attribute per code (zh needs zh-CN)
  var HTML_LANG = { zh: 'zh-CN' };

  var DICT = {
    'nav.home':    { en: 'Home',               zh: '首页',       es: 'Inicio',            fr: 'Accueil',         de: 'Start' },
    'nav.custom':  { en: 'Custom Pins',        zh: '定制徽章',    es: 'Pines',             fr: 'Pins Sur-Mesure',  de: 'Indiv. Pins' },
    'nav.how':     { en: 'How It Works',       zh: '制作流程',    es: 'Proceso',           fr: 'Processus',        de: 'Ablauf' },
    'nav.pricing': { en: 'Pricing',            zh: '价格',       es: 'Precios',           fr: 'Tarifs',          de: 'Preise' },
    'nav.gallery': { en: 'Gallery',            zh: '案例展示',    es: 'Galería',           fr: 'Galerie',         de: 'Galerie' },
    'nav.about':   { en: 'About',              zh: '关于我们',    es: 'Nosotros',          fr: 'À propos',        de: 'Über uns' },
    'nav.faq':     { en: 'FAQ',                zh: '常见问题',    es: 'FAQ',               fr: 'FAQ',             de: 'FAQ' },
    'nav.contact': { en: 'Contact',            zh: '联系我们',    es: 'Contacto',          fr: 'Contact',         de: 'Kontakt' },
    'cta.quote':   { en: 'Get a Free Quote',   zh: '免费获取报价', es: 'Solicitar Cotización', fr: 'Demander un Devis', de: 'Kostenloses Angebot' },
    'meta.title':  { en: 'Custom Enamel Pins & Badges | EnamelCraft', zh: '定制珐琅徽章与胸针 | EnamelCraft' },
    'meta.desc':   { en: 'EnamelCraft makes custom hard & soft enamel pins, lapel pins, brooches and badges. Free artwork, low minimums, worldwide shipping.', zh: 'EnamelCraft 专业定制硬珐琅 / 软珐琅徽章、胸针与奖牌。免费设计、低起订量、全球发货。' },

    'meta.title.home': { en: "Custom Enamel Pins & Badges | EnamelCraft", zh: "定制珐琅徽章与胸针 | EnamelCraft", es: "Pines y Insignias de Esmalte Personalizados | EnamelCraft", fr: "Épingles et Badges en Émail Personnalisés | EnamelCraft", de: "Individuelle Emailleschilder & Anstecknadeln | EnamelCraft" },
    'meta.desc.home': { en: "EnamelCraft makes custom hard & soft enamel pins, lapel pins, brooches and badges. Free artwork, low minimums, worldwide shipping.", zh: "EnamelCraft 专业定制硬珐琅 / 软珐琅徽章、胸针与奖牌。免费设计、低起订量、全球发货。", es: "EnamelCraft fabrica pines de esmalte duro y suave, insignias de solapa, broches y chapas personalizados. Arte gratis, pedidos mínimos bajos y envío mundial.", fr: "EnamelCraft fabrique des épingles en émail dur et tendre, insignes, broches et badges personnalisés. Artwork offert, petites quantités, livraison mondiale.", de: "EnamelCraft fertigt individuelle Hart- und Weichemail-Pins, Anstecknadeln, Broschen und Abzeichen. Kostenlose Gestaltung, niedrige Mindestmengen, weltweiter Versand." },
    'meta.title.custom': { en: "Custom Enamel Pins & Badges | EnamelCraft", zh: "定制珐琅徽章与胸针 | EnamelCraft", es: "Pines y Insignias de Esmalte Personalizados | EnamelCraft", fr: "Épingles et Badges en Émail Personnalisés | EnamelCraft", de: "Individuelle Emailleschilder & Anstecknadeln | EnamelCraft" },
    'meta.desc.custom': { en: "Hard enamel, soft enamel, lapel pins, brooches and custom badges in any size and finish. Free design and quote.", zh: "硬珐琅、软珐琅、领针、胸针与定制徽章，任意尺寸与工艺。免费设计与报价。", es: "Esmalte duro, esmalte suave, insignias de solapa, broches y chapas personalizadas en cualquier tamaño y acabado. Diseño y cotización gratis.", fr: "Émail dur, émail tendre, insignes, broches et badges personnalisés en toutes tailles et finitions. Conception et devis gratuits.", de: "Hartemail, Weichemail, Anstecknadeln, Broschen und individuelle Abzeichen in jeder Größe und Ausführung. Kostenlose Gestaltung und Angebot." },
    'meta.title.how': { en: "How It Works | EnamelCraft", zh: "制作流程 | EnamelCraft", es: "Cómo Funciona | EnamelCraft", fr: "Comment ça Marche | EnamelCraft", de: "So Funktioniert's | EnamelCraft" },
    'meta.desc.how': { en: "See how custom enamel pins are made — from your first idea to worldwide delivery in a few simple steps.", zh: "了解定制珐琅徽章的制作过程——从创意到全球送达，只需简单几步。", es: "Descubre cómo se fabrican los pines de esmalte, de tu primera idea a la entrega mundial en simples pasos.", fr: "Découvrez comment sont fabriquées les épingles en émail, de votre idée à la livraison mondiale.", de: "Sehen Sie, wie individuelle Emailleschilder entstehen — von der ersten Idee bis zur weltweiten Lieferung." },
    'meta.title.pricing': { en: "Pricing & Options | EnamelCraft", zh: "价格与方案 | EnamelCraft", es: "Precios y Opciones | EnamelCraft", fr: "Tarifs et Options | EnamelCraft", de: "Preise & Optionen | EnamelCraft" },
    'meta.desc.pricing': { en: "Transparent enamel pin pricing by quantity, size and finish. Low minimums and bulk discounts.", zh: "按数量、尺寸与工艺透明计价的珐琅徽章价格。低起订量，量大优惠。", es: "Precios transparentes de pines de esmalte según cantidad, tamaño y acabado. Pedidos mínimos bajos y descuentos por volumen.", fr: "Tarifs transparents des épingles en émail selon quantité, taille et finition. Petites quantités et remises de gros.", de: "Transparente Preise für Emailleschilder nach Menge, Größe und Ausführung. Niedrige Mindestmengen und Mengenrabatte." },
    'meta.title.gallery': { en: "Our Work | EnamelCraft", zh: "案例展示 | EnamelCraft", es: "Nuestro Trabajo | EnamelCraft", fr: "Nos Réalisations | EnamelCraft", de: "Unsere Arbeiten | EnamelCraft" },
    'meta.desc.gallery': { en: "A portfolio of custom enamel pins, badges and brooches made for brands, events and creators.", zh: "为品牌、活动与创作者定制的珐琅徽章、胸针与奖牌作品集。", es: "Un portafolio de pines, insignias y broches de esmalte hechos para marcas, eventos y creadores.", fr: "Un portfolio d'épingles, badges et broches en émail réalisés pour des marques, événements et créateurs.", de: "Ein Portfolio individueller Emailleschilder, Abzeichen und Broschen für Marken, Events und Creator." },
    'meta.title.about': { en: "About Us | EnamelCraft", zh: "关于我们 | EnamelCraft", es: "Sobre Nosotros | EnamelCraft", fr: "À propos de Nous | EnamelCraft", de: "Über Uns | EnamelCraft" },
    'meta.desc.about': { en: "EnamelCraft is a design-led enamel pin manufacturer with low minimums, free artwork and worldwide shipping.", zh: "EnamelCraft 是一家以设计为导向的珐琅徽章制造商，低起订量、免费设计、全球发货。", es: "EnamelCraft es un fabricante de pines de esmalte con enfoque en diseño, pedidos mínimos bajos, arte gratis y envío mundial.", fr: "EnamelCraft est un fabricant d'épingles en émail axé sur le design, avec petites quantités, artwork offert et livraison mondiale.", de: "EnamelCraft ist ein designorientierter Hersteller von Emailleschildern mit niedrigen Mindestmengen, kostenloser Gestaltung und weltweitem Versand." },
    'meta.title.faq': { en: "FAQ & Help | EnamelCraft", zh: "常见问题 | EnamelCraft", es: "Preguntas Frecuentes | EnamelCraft", fr: "FAQ & Aide | EnamelCraft", de: "FAQ & Hilfe | EnamelCraft" },
    'meta.desc.faq': { en: "Answers to common questions about minimums, files, turnaround, plating, shipping and our quality guarantee.", zh: "关于起订量、文件、交期、镀色、物流与品质保障的常见问题解答。", es: "Respuestas a preguntas comunes sobre pedidos mínimos, archivos, tiempos, chapado, envíos y nuestra garantía.", fr: "Réponses aux questions fréquentes sur les minimums, fichiers, délais, placage, livraison et notre garantie.", de: "Antworten auf häufige Fragen zu Mindestmengen, Dateien, Lieferzeit, Vergoldung, Versand und unserer Qualitätsgarantie." },
    'meta.title.contact': { en: "Contact & Free Quote | EnamelCraft", zh: "联系我们与免费报价 | EnamelCraft", es: "Contacto y Cotización Gratis | EnamelCraft", fr: "Contact et Devis Gratuit | EnamelCraft", de: "Kontakt & Kostenloses Angebot | EnamelCraft" },
    'meta.desc.contact': { en: "Request a free enamel pin quote. Send your idea and get a design proof within 24 hours.", zh: "免费获取珐琅徽章报价。提交您的创意，24 小时内获得设计稿。", es: "Solicita un presupuesto gratuito de pines de esmalte. Envía tu idea y recibe un diseño en 24 horas.", fr: "Demandez un devis gratuit d'épingles en émail. Envoyez votre idée et recevez une épreuve sous 24 h.", de: "Fordere ein kostenloses Angebot für Emailleschilder an. Sende deine Idee und erhalte einen Entwurf innerhalb von 24 Stunden." },
    'home.eyebrow.hero': { en: "Custom Enamel Pins & Badges", zh: "定制珐琅徽章与胸针", es: "Pines y Insignias de Esmalte Personalizados", fr: "Épingles et Badges en Émail Personnalisés", de: "Individuelle Emailleschilder & Anstecknadeln" },
    'home.hero.title': { en: "Enamel pins that make your <span class='hl'>brand unforgettable</span>", zh: "让您的<span class='hl'>品牌令人难忘</span>的珐琅徽章", es: "Pines de esmalte que hacen que tu <span class='hl'>marca sea inolvidable</span>", fr: "Des épingles en émail qui rendent votre <span class='hl'>marque inoubliable</span>", de: "Emailleschilder, die Ihre <span class='hl'>Marke unvergesslich</span> machen" },
    'home.hero.sub': { en: "We turn your logo, artwork or idea into premium hard & soft enamel pins, lapel pins and brooches — with free design, low minimums and worldwide shipping.", zh: "我们将您的 logo、设计或创意，打造成高端硬珐琅 / 软珐琅徽章、领针与胸针——免费设计、低起订量、全球发货。", es: "Convertimos tu logo, arte o idea en pines de esmalte premium duro y suave, insignias de solapa y broches, con diseño gratis, pedidos mínimos bajos y envío mundial.", fr: "Nous transformons votre logo, votre œuvre ou votre idée en épingles en émail dur et tendre haut de gamme, insignes et broches — avec conception gratuite, petites quantités et livraison mondiale.", de: "Wir verwandeln Ihr Logo, Ihr Design oder Ihre Idee in hochwertige Hart- und Weichemail-Pins, Anstecknadeln und Broschen — mit kostenloser Gestaltung, niedrigen Mindestmengen und weltweitem Versand." },
    'home.hero.cta2': { en: "View Our Work", zh: "查看我们的作品", es: "Ver Nuestro Trabajo", fr: "Voir Nos Réalisations", de: "Unsere Arbeiten ansehen" },
    'home.trust.artwork': { en: "Free artwork & proof", zh: "免费设计与打样", es: "Arte y muestra gratis", fr: "Artwork et épreuve offerts", de: "Kostenlose Gestaltung & Proof" },
    'home.trust.prod': { en: "7–12 day production", zh: "7–12 天生产", es: "Producción en 7–12 días", fr: "Production en 7–12 jours", de: "Produktion in 7–12 Tagen" },
    'home.trust.ship': { en: "Worldwide shipping", zh: "全球配送", es: "Envío mundial", fr: "Livraison mondiale", de: "Weltweiter Versand" },
    'home.trust.moq': { en: "Low MOQ from 100 pcs", zh: "低起订量 100 个起", es: "Pedido mínimo desde 100 uds", fr: "Petit minimum dès 100 pièces", de: "Niedrige Mindestmenge ab 100 Stk" },
    'home.make.eyebrow': { en: "What we make", zh: "我们的产品", es: "Lo que fabricamos", fr: "Ce que nous fabriquons", de: "Was wir fertigen" },
    'home.make.title': { en: "Custom pins, made your way", zh: "定制徽章，随心而定", es: "Pines personalizados, a tu manera", fr: "Épingles personnalisées, à votre goût", de: "Individuelle Pins, ganz nach Ihren Wünschen" },
    'home.make.lead': { en: "From corporate merch to event souvenirs and fan gear — pick a style and we'll handle the rest.", zh: "从企业周边到活动纪念品与粉丝周边——选个风格，其余交给我们。", es: "Desde merchandising corporativo hasta recuerdos de eventos y artículos de fans; elige un estilo y nosotros hacemos el resto.", fr: "Du goodies d'entreprise aux souvenirs d'événement et aux produits de fans — choisissez un style, nous nous occupons du reste.", de: "Vom Firmenmerch über Event-Souvenirs bis zur Fan-Ausrüstung — wählen Sie einen Stil, den Rest machen wir." },
    'home.make.tag': { en: "Popular", zh: "热销", es: "Popular", fr: "Populaire", de: "Beliebt" },
    'home.make.hard.desc': { en: "Smooth, polished finish flush with the metal — premium feel and crisp detail.", zh: "与金属齐平的顺滑抛光明面——高级质感，细节锐利。", es: "Acabado liso y pulido a ras del metal, sensación premium y detalle nítido.", fr: "Finition lisse et polie à fleur de métal — toucher premium et détail net.", de: "Glatte, polierte Oberfläche bündig mit dem Metall — Premium-Gefühl und scharfe Details." },
    'home.make.soft.desc': { en: "Textured recessed enamel with raised metal lines — cost-effective and vibrant.", zh: "凹陷珐琅配立体金属线——性价比高、色彩鲜艳。", es: "Esmalte texturizado recesado con líneas de metal elevadas, económico y vibrante.", fr: "Émail texturé encastré avec lignes métalliques surélevées — économique et vif.", de: "Strukturiertes, vertieftes Email mit erhabenen Metalllinien — kostengünstig und farbenfroh." },
    'home.make.lapel.desc': { en: "Elegant accents for uniforms, clubs and gifts, with butterfly or rubber clutches.", zh: "适用于制服、社团与礼赠的优雅点缀，配蝴蝶扣或橡胶扣。", es: "Detalles elegantes para uniformes, clubes y regalos, con broches mariposa o de goma.", fr: "Accents élégants pour uniformes, clubs et cadeaux, avec attache papillon ou caoutchouc.", de: "Elegante Akzente für Uniformen, Clubs und Geschenke, mit Schmetterlings- oder Gummiklemme." },
    'home.make.badge.desc': { en: "Button & enamel badges for events, schools and promotions — any shape, any size.", zh: "适用于活动、学校与促销的徽章与珐琅章——任意形状、任意尺寸。", es: "Insignias de botón y esmalte para eventos, escuelas y promociones, cualquier forma y tamaño.", fr: "Badges bouton et émail pour événements, écoles et promotions — toutes formes, toutes tailles.", de: "Button- und Emaileabzeichen für Events, Schulen und Werbeaktionen — jede Form, jede Größe." },
    'home.make.explore': { en: "Explore all products →", zh: "浏览全部产品 →", es: "Explorar todos los productos →", fr: "Explorer tous les produits →", de: "Alle Produkte ansehen →" },
    'home.how.eyebrow': { en: "How it works", zh: "制作流程", es: "Cómo funciona", fr: "Comment ça marche", de: "So funktioniert's" },
    'home.how.title': { en: "From idea to enamel in 5 steps", zh: "五步，从创意到珐琅成品", es: "De la idea al esmalte en 5 pasos", fr: "De l'idée à l'émail en 5 étapes", de: "In 5 Schritten von der Idee zum Email" },
    'home.step1.h': { en: "Send your idea", zh: "提交创意", es: "Envía tu idea", fr: "Envoyez votre idée", de: "Senden Sie Ihre Idee" },
    'home.step1.p': { en: "Upload a logo, sketch or description — any format welcome.", zh: "上传 logo、草图或描述——任何格式都欢迎。", es: "Sube un logo, boceto o descripción; cualquier formato es bienvenido.", fr: "Téléchargez un logo, un croquis ou une description — tout format accepté.", de: "Laden Sie ein Logo, eine Skizze oder Beschreibung hoch — jedes Format willkommen." },
    'home.step2.h': { en: "Free design & quote", zh: "免费设计与报价", es: "Diseño y cotización gratis", fr: "Conception et devis gratuits", de: "Kostenlose Gestaltung & Angebot" },
    'home.step2.p': { en: "We draft a digital proof and a no-obligation quote.", zh: "我们制作数字打样与无责任报价。", es: "Elaboramos una muestra digital y un presupuesto sin compromiso.", fr: "Nous rédigeons une épreuve numérique et un devis sans engagement.", de: "Wir erstellen einen digitalen Proof und ein unverbindliches Angebot." },
    'home.step3.h': { en: "Approve the proof", zh: "确认打样", es: "Aprueba la muestra", fr: "Approuvez l'épreuve", de: "Genehmigen Sie den Proof" },
    'home.step3.p': { en: "Tweak until it's perfect. Production starts on approval.", zh: "反复微调直到完美。确认后开始生产。", es: "Ajusta hasta que sea perfecto. La producción empieza tras la aprobación.", fr: "Ajustez jusqu'à la perfection. La production démarre à l'approbation.", de: "Feinjustieren bis perfekt. Die Produktion startet nach Freigabe." },
    'home.step4.h': { en: "We craft & ship", zh: "制作与发货", es: "Fabricamos y enviamos", fr: "Nous fabriquons et expédions", de: "Wir fertigen & versenden" },
    'home.step4.p': { en: "7–12 days production, then worldwide delivery to your door.", zh: "7–12 天生产，随后全球配送到家。", es: "Producción en 7–12 días, luego envío mundial a tu puerta.", fr: "Production en 7–12 jours, puis livraison mondiale à votre porte.", de: "Produktion in 7–12 Tagen, dann weltweiter Versand an Ihre Tür." },
    'home.how.cta': { en: "See the full process →", zh: "查看完整流程 →", es: "Ver el proceso completo →", fr: "Voir le processus complet →", de: "Den vollständigen Ablauf ansehen →" },
    'home.why.eyebrow': { en: "Why EnamelCraft", zh: "为何选择 EnamelCraft", es: "Por qué EnamelCraft", fr: "Pourquoi EnamelCraft", de: "Warum EnamelCraft" },
    'home.why.title': { en: "A partner, not just a printer", zh: "合作伙伴，而非只是工厂", es: "Un socio, no solo un impresor", fr: "Un partenaire, pas seulement un imprimeur", de: "Ein Partner, nicht nur ein Hersteller" },
    'home.why.free.h': { en: "Free artwork", zh: "免费设计", es: "Arte gratis", fr: "Artwork offert", de: "Kostenlose Gestaltung" },
    'home.why.free.p': { en: "Our designers turn rough ideas into production-ready proofs at no cost.", zh: "我们的设计师将粗略想法打磨成可生产的打样，完全免费。", es: "Nuestros diseñadores convierten ideas vagas en muestras listas para producción sin costo.", fr: "Nos designers transforment vos idées brutes en épreuves prêtes pour la production, gratuitement.", de: "Unsere Designer verwandeln grobe Ideen kostenlos in produktionsreife Proofs." },
    'home.why.fast.h': { en: "Fast turnaround", zh: "快速交付", es: "Entrega rápida", fr: "Délai rapide", de: "Schnelle Lieferzeit" },
    'home.why.fast.p': { en: "Standard 7–12 day production, with express options when you're in a rush.", zh: "标准 7–12 天生产，赶时间可选加急。", es: "Producción estándar en 7–12 días, con opciones exprés si tienes prisa.", fr: "Production standard en 7–12 jours, avec options express en cas d'urgence.", de: "Standardproduktion in 7–12 Tagen, mit Express-Option bei Zeitdruck." },
    'home.why.moq.h': { en: "Low minimums", zh: "低起订量", es: "Pedidos mínimos bajos", fr: "Petites quantités", de: "Niedrige Mindestmengen" },
    'home.why.moq.p': { en: "Start from just 100 pieces — perfect for small runs and test batches.", zh: "100 个即可起订——适合小批量与测试。", es: "Desde solo 100 piezas, ideal para tiradas pequeñas y pruebas.", fr: "À partir de seulement 100 pièces — parfait pour les petites séries et tests.", de: "Schon ab 100 Stück — ideal für Kleinserien und Testläufe." },
    'home.why.eco.h': { en: "Eco-conscious", zh: "环保理念", es: "Eco-consciente", fr: "Éco-responsable", de: "Umweltbewusst" },
    'home.why.eco.p': { en: "Recyclable metals and responsible plating for greener merch.", zh: "可回收金属与负责任镀色，让周边更环保。", es: "Metales reciclables y chapado responsable para un merchandising más verde.", fr: "Métaux recyclables et placage responsable pour un merchandising plus vert.", de: "Recyclingfähige Metalle und verantwortungsvolle Beschichtung für grüneres Merch." },
    'home.why.ship.h': { en: "Worldwide delivery", zh: "全球送达", es: "Entrega mundial", fr: "Livraison mondiale", de: "Weltweiter Versand" },
    'home.why.ship.p': { en: "Tracked shipping to 60+ countries with clear customs docs.", zh: "可追踪物流送至 60+ 国家，清关文件清晰。", es: "Envío rastreado a más de 60 países con documentos aduaneros claros.", fr: "Livraison suivie vers 60+ pays avec documents douaniers clairs.", de: "Nachverfolgbarer Versand in über 60 Länder mit klaren Zollunterlagen." },
    'home.why.quality.h': { en: "Quality guarantee", zh: "品质保障", es: "Garantía de calidad", fr: "Garantie qualité", de: "Qualitätsgarantie" },
    'home.why.quality.p': { en: "Not happy with the result? We'll remake or refund — no fuss.", zh: "对成品不满意？我们重做或退款——绝不推诿。", es: "¿No estás satisfecho? Repetimos o reembolsamos sin complicaciones.", fr: "Pas satisfait du résultat ? Nous refaisons ou remboursons — sans tracas.", de: "Nicht zufrieden? Wir fertigen neu oder erstatten — ohne Umstände." },
    'home.rev.eyebrow': { en: "What clients say", zh: "客户怎么说", es: "Lo que dicen los clientes", fr: "Ce que disent les clients", de: "Was Kunden sagen" },
    'home.rev.title': { en: "Loved by brands & creators", zh: "品牌与创作者的一致选择", es: "Amado por marcas y creadores", fr: "Adoré par les marques et créateurs", de: "Geliebt von Marken & Creatorn" },
    'home.rev1.p': { en: "“The hard enamel finish is incredible — our logo looks sharper than we imagined. Proof came back the same day.”", zh: "“硬珐琅的质感令人惊艳——我们的 logo 比想象中更锐利。当天就收到了打样。”", es: "“El acabado de esmalte duro es increíble; nuestro logo lució más nítido que lo imaginado. La muestra llegó el mismo día.”", fr: "« Le fini émail dur est incroyable — notre logo est plus net que prévu. L'épreuve est revenue le jour même. »", de: "„Die Hartemail-Oberfläche ist unglaublich — unser Logo wirkt schärfer als gedacht. Der Proof kam noch am selben Tag zurück.“" },
    'home.rev1.who': { en: "Maya R. <span>Brand Manager, Aurelia</span>", zh: "Maya R. <span>品牌经理，Aurelia</span>", es: "Maya R. <span>Brand Manager, Aurelia</span>", fr: "Maya R. <span>Brand Manager, Aurelia</span>", de: "Maya R. <span>Brand Manager, Aurelia</span>" },
    'home.rev2.p': { en: "“Low minimums let us test a fan pin for our launch. Turnaround was exactly as promised.”", zh: "“低起订量让我们能为新品首发试做粉丝徽章。交付时间与承诺完全一致。”", es: "“Los pedidos mínimos bajos nos permitieron probar un pin de fans para el lanzamiento. El plazo fue exactamente como prometieron.”", fr: "« Les petites quantités nous ont permis de tester une épingle fan pour notre lancement. Le délai a été exactement comme promis. »", de: "„Die niedrige Mindestmenge ließ uns eine Fan-Nadel für unseren Launch testen. Die Lieferzeit war exakt wie versprochen.“" },
    'home.rev2.who': { en: "Dean K. <span>Founder, Northloop</span>", zh: "Dean K. <span>创始人，Northloop</span>", es: "Dean K. <span>Fundador, Northloop</span>", fr: "Dean K. <span>Fondateur, Northloop</span>", de: "Dean K. <span>Gründer, Northloop</span>" },
    'home.rev3.p': { en: "“Communication was flawless across time zones. The brooches were a hit at our conference.”", zh: "“跨时区沟通毫无障碍。胸针在我们的会议上大受欢迎。”", es: "“La comunicación fue perfecta a pesar de los husos horarios. Los broches fueron un éxito en nuestra conferencia.”", fr: "« La communication était impeccable malgré les fuseaux horaires. Les broches ont eu un franc succès à notre conférence. »", de: "„Die Kommunikation über Zeitzonen hinweg war tadellos. Die Broschen kamen auf unserer Konferenz super an.“" },
    'home.rev3.who': { en: "Sofia L. <span>Event Lead, Meridian</span>", zh: "Sofia L. <span>活动负责人，Meridian</span>", es: "Sofia L. <span>Responsable de Eventos, Meridian</span>", fr: "Sofia L. <span>Cheffe d'Événement, Meridian</span>", de: "Sofia L. <span>Event-Leiterin, Meridian</span>" },
    'home.cta.title': { en: "Ready to make your enamel pins?", zh: "准备好制作您的珐琅徽章了吗？", es: "¿Listo para hacer tus pines de esmalte?", fr: "Prêt à créer vos épingles en émail ?", de: "Bereit für Ihre Emailleschilder?" },
    'home.cta.sub': { en: "Tell us about your project and get a free design proof & quote within 24 hours.", zh: "告诉我们您的项目，24 小时内获取免费设计打样与报价。", es: "Cuéntanos sobre tu proyecto y recibe una muestra de diseño y cotización gratis en 24 horas.", fr: "Parlez-nous de votre projet et recevez une épreuve de conception et un devis gratuits sous 24 h.", de: "Erzählen Sie uns von Ihrem Projekt und erhalten Sie innerhalb von 24 Stunden einen kostenlosen Design-Proof & Angebot." },
    'custom.eyebrow.hero': { en: "Our Products", zh: "我们的产品", es: "Nuestros Productos", fr: "Nos Produits", de: "Unsere Produkte" },
    'custom.hero.title': { en: "Custom <span class='hl'>enamel pins</span> & badges", zh: "定制<span class='hl'>珐琅徽章</span>与胸针", es: "Pines de <span class='hl'>esmalte</span> e insignias personalizados", fr: "Épingles en <span class='hl'>émail</span> et badges personnalisés", de: "Individuelle <span class='hl'>Emailleschilder</span> & Abzeichen" },
    'custom.hero.sub': { en: "Choose a style, a size and a finish — then let our team bring your design to life. Every order includes free artwork and a digital proof.", zh: "选好款式、尺寸与工艺——然后交给我们的团队实现您的设计。每笔订单均含免费设计与数字打样。", es: "Elige un estilo, un tamaño y un acabado; luego nuestro equipo da vida a tu diseño. Cada pedido incluye arte y muestra digital gratis.", fr: "Choisissez un style, une taille et une finition — puis notre équipe donne vie à votre design. Chaque commande inclut artwork et épreuve numérique offerts.", de: "Wählen Sie Stil, Größe und Finish — dann bringt unser Team Ihr Design zum Leben. Jede Bestellung enthält kostenlose Gestaltung und einen digitalen Proof." },
    'custom.hero.cta1': { en: "Request a Quote →", zh: "获取报价 →", es: "Solicitar Cotización →", fr: "Demander un Devis →", de: "Angebot anfordern →" },
    'custom.hero.cta2': { en: "How It Works", zh: "制作流程", es: "Cómo Funciona", fr: "Comment ça Marche", de: "So Funktioniert's" },
    'custom.hard.desc': { en: "Enamel is polished flush with the metal die, giving a smooth, glass-like surface. Best for premium merch, corporate gifts and collector pins where detail and durability matter.", zh: "珐琅与金属模具齐平抛光，呈现顺滑如玻璃的表面。最适合注重细节与耐久的高端周边、企业礼品与收藏徽章。", es: "El esmalte se pulle a ras del molde metálico, dando una superficie lisa y vidriosa. Ideal para merchandising premium, regalos corporativos y pines de colección donde importan el detalle y la durabilidad.", fr: "L'émail est poli à fleur du moule métallique, offrant une surface lisse et vitrée. Idéal pour le merchandising premium, les cadeaux d'entreprise et les épingles de collection où détail et durabilité comptent.", de: "Email wird bündig zum Metallstempel poliert und ergibt eine glatte, glasartige Oberfläche. Am besten für Premium-Merch, Firmengeschenke und Sammler-Pins, wo Detail und Haltbarkeit zählen." },
    'custom.soft.desc': { en: "Enamel sits below raised metal lines for a textured, tactile finish. The most popular and budget-friendly option, with vivid colours and fast production.", zh: "珐琅低于立体金属线，形成有纹理、可触摸的质感。最热门且经济实惠，色彩鲜艳、生产快速。", es: "El esmalte queda bajo líneas metálicas elevadas para un acabado texturizado y táctil. La opción más popular y económica, con colores vivos y producción rápida.", fr: "L'émail se situe sous des lignes métalliques surélevées pour un fini texturé et tactile. L'option la plus populaire et abordable, aux couleurs vives et production rapide.", de: "Email liegt unter erhabenen Metalllinien und ergibt eine strukturierte, haptische Oberfläche. Die beliebteste und budgetfreundlichste Option, mit leuchtenden Farben und schneller Produktion." },
    'custom.lapel.desc': { en: "Elegant wearable accents with secure clutches — butterfly, rubber or deluxe magnetic. Perfect for uniforms, clubs, milestones and fashion.", zh: "优雅的可佩戴点缀，配稳固扣具——蝴蝶扣、橡胶扣或高端磁扣。适用于制服、社团、纪念与时尚。", es: "Detalles elegantes y portátiles con broches seguros: mariposa, goma o magnético de lujo. Perfectos para uniformes, clubes, hitos y moda.", fr: "Accents élégants et portables avec attaches sûres — papillon, caoutchouc ou magnétique de luxe. Parfaits pour uniformes, clubs, jalons et mode.", de: "Elegante, tragbare Akzente mit sicheren Klemmen — Schmetterling, Gummio oder luxuriös magnetisch. Perfekt für Uniformen, Clubs, Meilensteine und Mode." },
    'custom.badge.desc': { en: "Round, square or fully custom shapes in enamel or button style. Great for schools, promotions, awareness campaigns and staff identification.", zh: "圆形、方形或完全定制的珐琅或纽扣式造型。非常适合学校、促销、公益宣传与员工识别。", es: "Formas redondas, cuadradas o totalmente personalizadas en esmalte o estilo botón. Ideales para escuelas, promociones, campañas de concientización e identificación de personal.", fr: "Formes rondes, carrées ou totalement personnalisées en émail ou style bouton. Parfaites pour écoles, promotions, campagnes de sensibilisation et identification du personnel.", de: "Runde, quadratische oder völlig individuelle Formen in Email- oder Button-Stil. Toll für Schulen, Promotionen, Awareness-Kampagnen und Mitarbeiterausweise." },
    'custom.hard.ideal': { en: "<b>Ideal for:</b> brand merch, awards, high-end giveaways.", zh: "<b>适合：</b>品牌周边、奖项、高端赠品。", es: "<b>Ideal para:</b> merchandising de marca, premios, regalos exclusivos.", fr: "<b>Idéal pour :</b> goodies de marque, récompenses, cadeaux haut de gamme.", de: "<b>Ideal für:</b> Marken-Merch, Auszeichnungen, hochwertige Giveaways." },
    'custom.soft.ideal': { en: "<b>Ideal for:</b> events, fundraisers, large runs.", zh: "<b>适合：</b>活动、募捐、大批量。", es: "<b>Ideal para:</b> eventos, recaudaciones de fondos, tiradas grandes.", fr: "<b>Idéal pour :</b> événements, collectes de fonds, grandes séries.", de: "<b>Ideal für:</b> Events, Spendenaktionen, Großserien." },
    'custom.lapel.ideal': { en: "<b>Ideal for:</b> uniforms, membership, gifts.", zh: "<b>适合：</b>制服、会员、礼赠。", es: "<b>Ideal para:</b> uniformes, membresías, regalos.", fr: "<b>Idéal pour :</b> uniformes, adhésions, cadeaux.", de: "<b>Ideal für:</b> Uniformen, Mitgliedschaften, Geschenke." },
    'custom.badge.ideal': { en: "<b>Ideal for:</b> events, schools, promo.", zh: "<b>适合：</b>活动、学校、促销。", es: "<b>Ideal para:</b> eventos, escuelas, promociones.", fr: "<b>Idéal pour :</b> événements, écoles, promo.", de: "<b>Ideal für:</b> Events, Schulen, Promo." },
    'custom.sizes.eyebrow': { en: "Sizes", zh: "尺寸", es: "Tamaños", fr: "Tailles", de: "Größen" },
    'custom.sizes.title': { en: "Common pin sizes", zh: "常见徽章尺寸", es: "Tamaños comunes de pines", fr: "Tailles courantes d'épingles", de: "Gängige Pinn-Größen" },
    'custom.sizes.lead': { en: "Need something else? We cut any size from 13mm to 100mm+. Sizes below are the most requested.", zh: "需要其他尺寸？我们可切割 13mm 至 100mm+ 任意规格。以下是咨询最多的尺寸。", es: "¿Necesitas otro tamaño? Cortamos cualquiera de 13 mm a 100 mm+. Los tamaños abajo son los más solicitados.", fr: "Besoin d'une autre taille ? Nous découpons toute taille de 13 mm à 100 mm+. Les tailles ci-dessous sont les plus demandées.", de: "Brauchen Sie etwas anderes? Wir schneiden jede Größe von 13 mm bis 100 mm+. Die unten genannten sind am meisten gefragt." },
    'custom.size1.desc': { en: "Subtle, minimalist accents", zh: "精致、极简的点缀", es: "Detalles sutiles y minimalistas", fr: "Accents subtils et minimalistes", de: "Dezente, minimalistische Akzente" },
    'custom.size2.desc': { en: "Most popular everyday size", zh: "最受欢迎的日常尺寸", es: "El tamaño diario más popular", fr: "La taille quotidienne la plus populaire", de: "Beliebteste Alltagsgröße" },
    'custom.size3.desc': { en: "Bold, detailed designs", zh: "醒目、细节丰富的设计", es: "Diseños audaces y detallados", fr: "Designs audacieux et détaillés", de: "Kühne, detailreiche Designs" },
    'custom.size4.desc': { en: "Statement & photo pins", zh: "个性款与照片徽章", es: "Pines de declaración y fotos", fr: "Épingles statement et photos", de: "Statement- & Foto-Pins" },
    'custom.fin.eyebrow': { en: "Finishes", zh: "工艺", es: "Acabados", fr: "Finitons", de: "Ausführungen" },
    'custom.fin.title': { en: "Plating & options", zh: "镀色与选项", es: "Chapado y opciones", fr: "Placage et options", de: "Vergoldung & Optionen" },
    'custom.fin.plating.h': { en: "Plating", zh: "镀色", es: "Chapado", fr: "Placage", de: "Vergoldung" },
    'custom.fin.plating.p': { en: "Gold, silver, rose gold, black nickel, antique brass & copper — matched to your artwork.", zh: "金色、银色、玫瑰金、黑镍、古铜与古铜红——与您的设计匹配。", es: "Oro, plata, oro rosa, níquel negro, latón y cobre antiguo, a juego con tu arte.", fr: "Or, argent, or rose, nickel noir, laiton et cuivre vieilli — accordés à votre œuvre.", de: "Gold, Silber, Roségold, Schwarz-Nickel, antik Messing & Kupfer — abgestimmt auf Ihr Design." },
    'custom.fin.attach.h': { en: "Attachments", zh: "配件", es: "Accesorios", fr: "Fixations", de: "Befestigungen" },
    'custom.fin.attach.p': { en: "Butterfly clutch, rubber clutch, magnetic, screw & cap, or brooch hook.", zh: "蝴蝶扣、橡胶扣、磁扣、螺钉帽扣或胸针扣。", es: "Broche mariposa, broche de goma, magnético, tornillo y tapa, o gancho de broche.", fr: "Attache papillon, caoutchouc, magnétique, vis et chapeau, ou crochet de broche.", de: "Schmetterlingsklemme, Gummiklemme, magnetisch, Schraub- & Kappenverschluss oder Broschenhaken." },
    'custom.fin.extras.h': { en: "Extras", zh: "附加项", es: "Extras", fr: "Options", de: "Extras" },
    'custom.fin.extras.p': { en: "Glitter & glow enamel, epoxy dome, cut-outs, sliders and printed details.", zh: "闪粉与夜光珐琅、滴胶圆顶、镂空、滑块与印刷细节。", es: "Esmalte con purpurina y brillante, domo de resina, recortes, deslizadores y detalles impresos.", fr: "Émail pailleté et phosphorescent, dôme époxy, découpes, glisseurs et détails imprimés.", de: "Glitzer- & Glow-Email, Epoxid-Kuppel, Ausstanzungen, Schieber und gedruckte Details." },
    'custom.fin.cta': { en: "Tell us your idea →", zh: "告诉我们您的想法 →", es: "Cuéntanos tu idea →", fr: "Parlez-nous de votre idée →", de: "Erzählen Sie uns Ihre Idee →" },
    'how.eyebrow.hero': { en: "Process", zh: "流程", es: "Proceso", fr: "Processus", de: "Ablauf" },
    'how.hero.title': { en: "How it <span class='hl'>works</span>", zh: "如何<span class='hl'>制作</span>", es: "Cómo <span class='hl'>funciona</span>", fr: "Comment ça <span class='hl'>marche</span>", de: "Wie es <span class='hl'>funktioniert</span>" },
    'how.hero.sub': { en: "Ordering custom enamel pins should be simple. Here's exactly what happens from your first message to delivery.", zh: "定制珐琅徽章本应简单。以下是从您第一次联系到收货的完整过程。", es: "Pedir pines de esmalte personalizados debe ser simple. Esto es exactamente lo que ocurre desde tu primer mensaje hasta la entrega.", fr: "Commander des épingles en émail personnalisées devrait être simple. Voici exactement ce qui se passe de votre premier message à la livraison.", de: "Individuelle Emailleschilder zu bestellen sollte einfach sein. Hier ist genau, was von Ihrer ersten Nachricht bis zur Lieferung passiert." },
    'how.hero.cta': { en: "Start your project →", zh: "启动您的项目 →", es: "Inicia tu proyecto →", fr: "Lancez votre projet →", de: "Starten Sie Ihr Projekt →" },
    'how.step1.h': { en: "1 · Share your idea", zh: "1 · 分享您的创意", es: "1 · Comparte tu idea", fr: "1 · Partagez votre idée", de: "1 · Teilen Sie Ihre Idee" },
    'how.step1.p': { en: "Send a logo, sketch, photo or even a rough description. PDF, PNG, AI, SVG — we accept them all.", zh: "发送 logo、草图、照片甚至粗略描述。PDF、PNG、AI、SVG——我们全部接受。", es: "Envía un logo, boceto, foto o incluso una descripción aproximada. PDF, PNG, AI, SVG; aceptamos todo.", fr: "Envoyez un logo, croquis, photo ou même une description approximative. PDF, PNG, AI, SVG — tout nous convient.", de: "Senden Sie ein Logo, eine Skizze, ein Foto oder sogar eine grobe Beschreibung. PDF, PNG, AI, SVG — wir nehmen alles." },
    'how.step2.h': { en: "2 · Free design & quote", zh: "2 · 免费设计与报价", es: "2 · Diseño y cotización gratis", fr: "2 · Conception et devis gratuits", de: "2 · Kostenlose Gestaltung & Angebot" },
    'how.step2.p': { en: "Our designers create a digital proof and we send a clear, no-obligation quote within 24 hours.", zh: "我们的设计师制作数字打样，并在 24 小时内发送清晰的无责任报价。", es: "Nuestros diseñadores crean una muestra digital y enviamos un presupuesto claro y sin compromiso en 24 horas.", fr: "Nos designers créent une épreuve numérique et nous envoyons un devis clair et sans engagement sous 24 h.", de: "Unsere Designer erstellen einen digitalen Proof und senden innerhalb von 24 Stunden ein klares, unverbindliches Angebot." },
    'how.step3.h': { en: "3 · Approve the proof", zh: "3 · 确认打样", es: "3 · Aprueba la muestra", fr: "3 · Approuvez l'épreuve", de: "3 · Genehmigen Sie den Proof" },
    'how.step3.p': { en: "Request changes until it's perfect. Production only begins once you give the green light.", zh: "可要求修改直到完美。只有您点头，生产才会开始。", es: "Pide cambios hasta que sea perfecto. La producción solo empieza cuando das el visto bueno.", fr: "Demandez des modifications jusqu'à la perfection. La production démarre seulement après votre feu vert.", de: "Fordern Sie Änderungen an, bis es perfekt ist. Die Produktion beginnt erst nach Ihrer Freigabe." },
    'how.step4.h': { en: "4 · Production", zh: "4 · 生产", es: "4 · Producción", fr: "4 · Production", de: "4 · Produktion" },
    'how.step4.p': { en: "Tooling, enamel filling, polishing and QC. Standard 7–12 working days; express available.", zh: "开模、填珐琅、抛光与质检。标准 7–12 个工作日；支持加急。", es: "Molde, relleno de esmalte, pulido y control de calidad. Estándar 7–12 días hábiles; exprés disponible.", fr: "Outillage, remplissage d'émail, polissage et QC. Standard 7–12 jours ouvrés ; express disponible.", de: "Werkzeug, Emailbefüllung, Politur und QC. Standard 7–12 Werktage; Express möglich." },
    'how.step5.h': { en: "5 · Worldwide delivery", zh: "5 · 全球配送", es: "5 · Entrega mundial", fr: "5 · Livraison mondiale", de: "5 · Weltweiter Versand" },
    'how.step5.p': { en: "Carefully packed and shipped with tracking to 60+ countries, including customs paperwork.", zh: "精心包装并附追踪物流，送达 60+ 国家，含清关文件。", es: "Empaquetado con cuidado y enviado con seguimiento a más de 60 países, incluidos documentos aduaneros.", fr: "Soigneusement emballé et expédié avec suivi vers 60+ pays, documents douaniers inclus.", de: "Sorgfältig verpackt und mit Sendungsverfolgung in über 60 Länder verschickt, inklusive Zollpapieren." },
    'how.step6.h': { en: "6 · Aftercare", zh: "6 · 售后", es: "6 · Cuidado posterior", fr: "6 · Suivi", de: "6 · Betreuung" },
    'how.step6.p': { en: "Not satisfied? Our quality guarantee means we remake or refund — your project is safe with us.", zh: "不满意？我们的品质保障意味着重做或退款——您的项目在我们这里很安全。", es: "¿No satisfecho? Nuestra garantía de calidad significa que repetimos o reembolsamos; tu proyecto está seguro con nosotros.", fr: "Pas satisfait ? Notre garantie qualité signifie que nous refaisons ou remboursons — votre projet est en sécurité avec nous.", de: "Nicht zufrieden? Unsere Qualitätsgarantie bedeutet: wir fertigen neu oder erstatten — Ihr Projekt ist bei uns sicher." },
    'how.cta1': { en: "See pricing →", zh: "查看价格 →", es: "Ver precios →", fr: "Voir les tarifs →", de: "Preise ansehen →" },
    'how.cta2': { en: "View past work", zh: "查看过往作品", es: "Ver trabajos anteriores", fr: "Voir les réalisations passées", de: "Frühere Arbeiten ansehen" },
    'how.cta.title': { en: "Got a deadline? We can help.", zh: "有截止日期？我们能帮上忙。", es: "¿Tienes una fecha límite? Podemos ayudar.", fr: "Une date limite ? Nous pouvons aider.", de: "Termin unter Druck? Wir können helfen." },
    'how.cta.sub': { en: "Tell us your date and we'll suggest the fastest viable option — often without extra cost.", zh: "告诉我们您的日期，我们会建议最快可行方案——通常不额外收费。", es: "Dinos tu fecha y sugeriremos la opción viable más rápida, a menudo sin costo extra.", fr: "Indiquez-nous votre date et nous proposerons l'option la plus rapide — souvent sans frais supplémentaires.", de: "Nennen Sie uns Ihr Datum und wir schlagen die schnellste machbare Option vor — oft ohne Mehrkosten." },
    'pricing.eyebrow.hero': { en: "Pricing", zh: "价格", es: "Precios", fr: "Tarifs", de: "Preise" },
    'pricing.hero.title': { en: "Transparent <span class='hl'>pricing</span>", zh: "透明<span class='hl'>价格</span>", es: "Precios <span class='hl'>transparentes</span>", fr: "Tarifs <span class='hl'>transparents</span>", de: "Transparente <span class='hl'>Preise</span>" },
    'pricing.hero.sub': { en: "Enamel pin pricing depends on quantity, size, style and finish. Below are typical starting points — your final quote is tailored to your exact specs.", zh: "珐琅徽章价格取决于数量、尺寸、款式与工艺。以下是典型起价——最终报价将按您的精确规格定制。", es: "El precio de los pines de esmalte depende de cantidad, tamaño, estilo y acabado. Abajo hay puntos de partida típicos; tu cotización final se adapta a tus especificaciones.", fr: "Le tarif des épingles en émail dépend de la quantité, taille, style et finition. Voici des points de départ typiques — votre devis final est adapté à vos specs exactes.", de: "Der Preis für Emailleschilder hängt von Menge, Größe, Stil und Finish ab. Unten typische Einstiegspreise — Ihr finales Angebot wird exakt auf Ihre Specs zugeschnitten." },
    'pricing.hero.cta': { en: "Get your quote →", zh: "获取报价 →", es: "Obtén tu cotización →", fr: "Obtenez votre devis →", de: "Ihr Angebot erhalten →" },
    'pricing.rates.eyebrow': { en: "Indicative rates", zh: "参考价格", es: "Tarifas indicativas", fr: "Tarifs indicatifs", de: "Richtpreise" },
    'pricing.rates.title': { en: "Soft enamel, per-piece (USD)", zh: "软珐琅，单件价格（美元）", es: "Esmalte suave, por pieza (USD)", fr: "Émail tendre, par pièce (USD)", de: "Weichemail, pro Stück (USD)" },
    'pricing.rates.lead': { en: "Example for a 25mm soft enamel pin. Hard enamel and extras are quoted separately.", zh: "以 25mm 软珐琅徽章为例。硬珐琅与附加项另计。", es: "Ejemplo para un pin de esmalte suave de 25 mm. Esmalte duro y extras se cotizan aparte.", fr: "Exemple pour une épingle émail tendre de 25 mm. Émail dur et options sont devisés séparément.", de: "Beispiel für eine Weichemail-Nadel 25 mm. Hartemail und Extras werden separat kalkuliert." },
    'pricing.th.qty': { en: "Quantity", zh: "数量", es: "Cantidad", fr: "Quantité", de: "Menge" },
    'pricing.th.piece': { en: "Per piece", zh: "单价", es: "Por pieza", fr: "Par pièce", de: "Pro Stück" },
    'pricing.th.mould': { en: "Mould fee", zh: "模具费", es: "Molde", fr: "Frais de moule", de: "Werkzeugkosten" },
    'pricing.th.best': { en: "Best for", zh: "适合", es: "Ideal para", fr: "Idéal pour", de: "Geeignet für" },
    'pricing.mould.onetime': { en: "one-time $45", zh: "一次性 $45", es: "único $45", fr: "unique $45", de: "einmalig $45" },
    'pricing.free': { en: "Free", zh: "免费", es: "Gratis", fr: "Offert", de: "Kostenlos" },
    'pricing.best1': { en: "Test batch", zh: "测试批次", es: "Lote de prueba", fr: "Lot de test", de: "TestCharge" },
    'pricing.best2': { en: "Small event", zh: "小型活动", es: "Evento pequeño", fr: "Petit événement", de: "Kleine Veranstaltung" },
    'pricing.best3': { en: "Launch", zh: "新品发布", es: "Lanzamiento", fr: "Lancement", de: "Launch" },
    'pricing.best4': { en: "Campaign", zh: "营销活动", es: "Campaña", fr: "Campagne", de: "Kampagne" },
    'pricing.best5': { en: "Bulk / merch", zh: "大批量 / 周边", es: "Mayor / merchandising", fr: "Gros / merchandising", de: "Großmenge / Merch" },
    'pricing.note': { en: "* Indicative only. Final pricing depends on size, plating, attachments and artwork complexity. Mould fees are waived on larger runs. Shipping quoted separately.", zh: "* 仅供参考。最终价格取决于尺寸、镀色、配件与图案复杂度。大批量免模具费。运费另计。", es: "* Solo indicativo. El precio final depende de tamaño, chapado, accesorios y complejidad del arte. Se omiten moldes en tiradas grandes. Envío se cotiza aparte.", fr: "* Indicatif uniquement. Le prix final dépend taille, placage, fixations et complexité de l'œuvre. Frais de moule supprimés sur grandes séries. Livraison devisée séparément.", de: "* Nur Richtwert. Der Endpreis hängt von Größe, Vergoldung, Befestigung und Motivkomplexität ab. Werkzeugkosten ab Großserien entfallen. Versand separat kalkuliert." },
    'pricing.card1.h': { en: "Low MOQ", zh: "低起订量", es: "Pedido mínimo bajo", fr: "Petit minimum", de: "Niedrige Mindestmenge" },
    'pricing.card1.p': { en: "Order as few as 100 pieces — ideal for testing a design or a limited drop.", zh: "最少 100 个即可——适合测试设计或限量发售。", es: "Pide desde solo 100 piezas, ideal para probar un diseño o un lanzamiento limitado.", fr: "Commandez dès 100 pièces — idéal pour tester un design ou un drop limité.", de: "Schon ab 100 Stück bestellen — ideal zum Testen eines Designs oder eines limitierten Drops." },
    'pricing.card2.h': { en: "Bulk discounts", zh: "量大优惠", es: "Descuentos por volumen", fr: "Remises de gros", de: "Mengenrabatte" },
    'pricing.card2.p': { en: "The more you order, the lower the unit price, and mould fees drop away.", zh: "订得越多，单价越低，模具费也随之免除。", es: "Cuanto más pides, más baja la unidad, y los moldes se eliminan.", fr: "Plus vous commandez, plus le prix unitaire baisse, et les frais de moule disparaissent.", de: "Je mehr Sie bestellen, desto niedriger der Stückpreis, und Werkzeugkosten entfallen." },
    'pricing.card3.h': { en: "No hidden fees", zh: "无隐藏费用", es: "Sin cargos ocultos", fr: "Sans frais cachés", de: "Keine versteckten Gebühren" },
    'pricing.card3.p': { en: "Artwork, proofing and revisions are included. You see the full cost up front.", zh: "设计、打样与修改均包含在内。您事先即可看到全部费用。", es: "Arte, muestras y revisiones incluidos. Ves el costo total por adelantado.", fr: "Artwork, épreuves et révisions inclus. Vous voyez le coût total d'avance.", de: "Gestaltung, Proofing und Korrekturen inklusive. Sie sehen die Gesamtkosten im Voraus." },
    'pricing.cta': { en: "Request a tailored quote →", zh: "获取专属报价 →", es: "Solicitar cotización a medida →", fr: "Demander un devis sur mesure →", de: "Individuelles Angebot anfordern →" },
    'gallery.eyebrow.hero': { en: "Portfolio", zh: "作品集", es: "Portafolio", fr: "Portfolio", de: "Portfolio" },
    'gallery.hero.title': { en: "Our <span class='hl'>work</span>", zh: "我们的<span class='hl'>作品</span>", es: "Nuestro <span class='hl'>trabajo</span>", fr: "Nos <span class='hl'>réalisations</span>", de: "Unsere <span class='hl'>Arbeiten</span>" },
    'gallery.hero.sub': { en: "A glimpse of enamel pins, badges and brooches we've produced for brands, events and creators. Yours could be next.", zh: "我们为品牌、活动与创作者制作的珐琅徽章、胸针与奖牌一瞥。下一个也许就是您的。", es: "Un vistazo a los pines, insignias y broches de esmalte que hemos hecho para marcas, eventos y creadores. El tuyo podría ser el próximo.", fr: "Un aperçu des épingles, badges et broches en émail que nous avons produits pour des marques, événements et créateurs. Le vôtre pourrait être le prochain.", de: "Ein Blick auf die Emailleschilder, Abzeichen und Broschen, die wir für Marken, Events und Creator gefertigt haben. Ihres könnte das nächste sein." },
    'gallery.hero.cta': { en: "Start yours →", zh: "开始您的定制 →", es: "Inicia el tuyo →", fr: "Lancez le vôtre →", de: "Starten Sie Ihren →" },
    'gallery.filter.all': { en: "All", zh: "全部", es: "Todos", fr: "Tout", de: "Alle" },
    'gallery.filter.brand': { en: "Brand & Logo", zh: "品牌与 Logo", es: "Marca y Logo", fr: "Marque & Logo", de: "Marke & Logo" },
    'gallery.filter.event': { en: "Events", zh: "活动", es: "Eventos", fr: "Événements", de: "Events" },
    'gallery.filter.fan': { en: "Fan & Creator", zh: "粉丝与创作者", es: "Fans y Creadores", fr: "Fans & Créateurs", de: "Fans & Creator" },
    'gallery.filter.brooch': { en: "Brooches", zh: "胸针", es: "Broches", fr: "Broches", de: "Broschen" },
    'gallery.note': { en: "Real product photos from our workshop. <a href='contact.html'>Get a similar pin made →</a>", zh: "我们车间的真实产品照片。<a href='contact.html'>定制同款徽章 →</a>", es: "Fotos reales de productos de nuestro taller. <a href='contact.html'>Haz un pin similar →</a>", fr: "Vraies photos produit de notre atelier. <a href='contact.html'>Faire une épingle similaire →</a>", de: "Echte Produktfotos aus unserer Werkstatt. <a href='contact.html'>Ähnliche Nadel fertigen →</a>" },
    'gallery.cta': { en: "Get a similar pin made →", zh: "定制同款徽章 →", es: "Haz un pin similar →", fr: "Faire une épingle similaire →", de: "Ähnliche Nadel fertigen →" },
    'about.eyebrow.hero': { en: "About", zh: "关于", es: "Sobre", fr: "À propos", de: "Über" },
    'about.hero.title': { en: "We are <span class='hl'>EnamelCraft</span>", zh: "我们就是<span class='hl'>EnamelCraft</span>", es: "Somos <span class='hl'>EnamelCraft</span>", fr: "Nous sommes <span class='hl'>EnamelCraft</span>", de: "Wir sind <span class='hl'>EnamelCraft</span>" },
    'about.hero.sub': { en: "A small, design-led manufacturer helping brands and creators turn ideas into beautiful, durable enamel pins — without the usual minimum-order headaches.", zh: "一家以设计为导向的小型制造商，帮助品牌与创作者将创意变成美观耐用的珐琅徽章——免去常见的起订量烦恼。", es: "Un pequeño fabricante orientado al diseño que ayuda a marcas y creadores a convertir ideas en pines de esmalte hermosos y duraderos, sin los habituales dolores de cabeza por pedidos mínimos.", fr: "Un petit fabricant axé sur le design qui aide les marques et créateurs à transformer des idées en épingles en émail belles et durables — sans les habituels soucis de commande minimum.", de: "Ein kleiner, designorientierter Hersteller, der Marken und Creatorn hilft, Ideen in schöne, langlebige Emailleschilder zu verwandeln — ohne die üblichen Mindestbestell-Kopfschmerzen." },
    'about.hero.cta': { en: "Work with us →", zh: "与我们合作 →", es: "Trabaja con nosotros →", fr: "Travaillons ensemble →", de: "Arbeiten Sie mit uns →" },
    'about.story.eyebrow': { en: "Our story", zh: "我们的故事", es: "Nuestra historia", fr: "Notre histoire", de: "Unsere Geschichte" },
    'about.story.title': { en: "Craft meets convenience", zh: "匠心遇见便捷", es: "Artesanía y comodidad", fr: "Le savoir-faire rencontre la simplicité", de: "Handwerk trifft Bequemlichkeit" },
    'about.story.lead': { en: "EnamelCraft started with a simple frustration: great custom pins were locked behind huge minimums and slow, opaque processes. We built the studio we wished existed — free artwork, honest quotes, low minimums and a genuinely friendly team. Today we ship to clients in 60+ countries, from solo creators to global brands.", zh: "EnamelCraft 始于一个简单的痛点：优质的定制徽章被高起订量、缓慢且不透明的流程所困。我们打造了理想中的工作室——免费设计、诚实报价、低起订量，以及真正友善的团队。如今我们向 60+ 国家的客户发货，从个人创作者到全球品牌。", es: "EnamelCraft comenzó con una frustración simple: los buenos pines personalizados estaban atrapados tras pedidos mínimos enormes y procesos lentos y opacos. Construimos el estudio que deseábamos: arte gratis, cotizaciones honestas, pedidos mínimos bajos y un equipo verdaderamente amable. Hoy enviamos a clientes en más de 60 países, desde creadores solitarios hasta marcas globales.", fr: "EnamelCraft a démarré avec une frustration simple : de superbes épingles personnalisées étaient bloquées derrière d'énormes minimums et des processus lents et opaques. Nous avons bâti le studio que nous voulions voir exister — artwork offert, devis honnêtes, petites quantités et une équipe vraiment sympathique. Aujourd'hui nous expédions à des clients dans 60+ pays, des créateurs solo aux marques mondiales.", de: "EnamelCraft begann mit einer einfachen Frustration: gute individuelle Pins steckten hinter riesigen Mindestmengen und langsamen, undurchsichtigen Prozessen. Wir bauten das Studio, das wir uns wünschten — kostenlose Gestaltung, ehrliche Angebote, niedrige Mindestmengen und ein wirklich freundliches Team. Heute versenden wir an Kunden in über 60 Ländern, von Solo-Creatorn bis zu globalen Marken." },
    'about.stat1.lbl': { en: "Minimum order", zh: "起订量", es: "Pedido mínimo", fr: "Commande minimum", de: "Mindestbestellung" },
    'about.stat2.lbl': { en: "Countries shipped", zh: "已发货国家", es: "Países enviados", fr: "Pays livrés", de: "Belieferte Länder" },
    'about.stat3.lbl': { en: "Days to produce", zh: "生产天数", es: "Días de producción", fr: "Jours de production", de: "Produktionstage" },
    'about.stat4.lbl': { en: "Quote turnaround", zh: "报价周期", es: "Tiempo de cotización", fr: "Délai de devis", de: "Angebotszeit" },
    'about.why.eyebrow': { en: "Why choose us", zh: "为何选择我们", es: "Por qué elegirnos", fr: "Pourquoi nous choisir", de: "Warum uns wählen" },
    'about.why.title': { en: "Built for makers", zh: "为创作者而生", es: "Hecho para creadores", fr: "Conçu pour les créateurs", de: "Für Maker gebaut" },
    'about.wcu1.h': { en: "Design-first", zh: "设计优先", es: "Diseño primero", fr: "Design d'abord", de: "Design zuerst" },
    'about.wcu1.p': { en: "We sweat the proof so the final pin is exactly right — revisions included.", zh: "我们死磕打样，确保成品徽章分毫不差——含修改。", es: "Cuidamos la muestra para que el pin final sea exacto, revisiones incluidas.", fr: "Nous soignons l'épreuve pour que l'épingle finale soit parfaite — révisions incluses.", de: "Wir kümmern uns um den Proof, damit die finale Nadel exakt stimmt — Korrekturen inklusive." },
    'about.wcu2.h': { en: "Flexible runs", zh: "灵活起订", es: "Tiradas flexibles", fr: "Séries flexibles", de: "Flexible Serien" },
    'about.wcu2.p': { en: "From 100 test pieces to 10,000 merch drops, same care on every order.", zh: "从 100 个测试件到 10,000 件周边，每笔订单同等用心。", es: "Desde 100 piezas de prueba hasta 10 000 lotes de merchandising, el mismo cuidado en cada pedido.", fr: "De 100 pièces de test à 10 000 lots de merchandising, le même soin à chaque commande.", de: "Von 100 Teststücken bis 10.000 Merch-Drops, dieselbe Sorgfalt bei jeder Bestellung." },
    'about.wcu3.h': { en: "Global & local", zh: "全球与本土", es: "Global y local", fr: "Global et local", de: "Global & lokal" },
    'about.wcu3.p': { en: "Worldwide shipping with the personal touch of a boutique studio.", zh: "全球配送，兼具精品工作室的人情味。", es: "Envío mundial con el toque personal de un estudio boutique.", fr: "Livraison mondiale avec le contact personnel d'un studio boutique.", de: "Weltweiter Versand mit der persönlichen Note eines Boutique-Studios." },
    'about.wcu4.h': { en: "Responsible", zh: "负责任", es: "Responsable", fr: "Responsable", de: "Verantwortungsvoll" },
    'about.wcu4.p': { en: "Recyclable metals, responsible plating, minimal packaging waste.", zh: "可回收金属、负责任的镀色、最少包装浪费。", es: "Metales reciclables, chapado responsable, mínimo desperdicio de empaque.", fr: "Métaux recyclables, placage responsable, déchets d'emballage minimaux.", de: "Recyclingfähige Metalle, verantwortungsvolle Beschichtung, minimaler Verpackungsabfall." },
    'about.wcu5.h': { en: "Fast & clear", zh: "快速透明", es: "Rápido y claro", fr: "Rapide et clair", de: "Schnell & klar" },
    'about.wcu5.p': { en: "No black boxes — you always know status, cost and timeline.", zh: "没有黑箱——您随时掌握状态、费用与进度。", es: "Sin cajas negras; siempre sabes estado, costo y plazos.", fr: "Pas de boîtes noires — vous connaissez toujours statut, coût et calendrier.", de: "Keine Blackboxes — Sie wissen immer Stand, Kosten und Zeitplan." },
    'about.wcu6.h': { en: "Guaranteed", zh: "有保障", es: "Garantizado", fr: "Garanti", de: "Garantiert" },
    'about.wcu6.p': { en: "If it's not right, we make it right. That's the whole deal.", zh: "若不满意，我们负责到底。这就是我们的承诺。", es: "Si no está bien, lo arreglamos. Ese es el trato.", fr: "Si ce n'est pas bon, nous réparons. C'est tout l'accord.", de: "Wenn es nicht stimmt, machen wir es richtig. Das ist der Deal." },
    'faq.eyebrow.hero': { en: "Help", zh: "帮助", es: "Ayuda", fr: "Aide", de: "Hilfe" },
    'faq.hero.title': { en: "Frequently asked <span class='hl'>questions</span>", zh: "常见<span class='hl'>问题</span>", es: "Preguntas <span class='hl'>frecuentes</span>", fr: "Questions <span class='hl'>fréquentes</span>", de: "Häufig gestellte <span class='hl'>Fragen</span>" },
    'faq.hero.sub': { en: "Everything you need to know before starting your enamel pin project. Still stuck? We're one message away.", zh: "开启珐琅徽章项目前您需要了解的一切。还有疑问？随时给我们发消息。", es: "Todo lo que necesitas saber antes de iniciar tu proyecto de pines de esmalte. ¿Aún con dudas? Estamos a un mensaje de distancia.", fr: "Tout ce qu'il faut savoir avant de lancer votre projet d'épingles en émail. Bloqué ? Nous sommes à un message.", de: "Alles, was Sie vor Ihrem Emailleschilder-Projekt wissen müssen. Noch festgefahren? Wir sind eine Nachricht entfernt." },
    'faq.hero.cta': { en: "Ask us anything →", zh: "随时咨询 →", es: "Pregúntanos lo que sea →", fr: "Demandez-nous tout →", de: "Fragen Sie uns alles →" },
    'faq.q1': { en: "What is the minimum order quantity?", zh: "最小起订量是多少？", es: "¿Cuál es la cantidad mínima de pedido?", fr: "Quelle est la quantité de commande minimum ?", de: "Wie ist die Mindestbestellmenge?" },
    'faq.a1': { en: "Our standard minimum is 100 pieces per design. This lets you test a concept or run a limited edition without over-committing.", zh: "标准起订量为每款 100 个。这样您可以在不过度投入的情况下测试概念或做限量版。", es: "Nuestro mínimo estándar es de 100 piezas por diseño. Esto te permite probar un concepto o hacer una edición limitada sin comprometerte de más.", fr: "Notre minimum standard est de 100 pièces par design. Cela vous permet de tester un concept ou une édition limitée sans trop vous engager.", de: "Unsere Standard-Mindestmenge beträgt 100 Stück pro Design. So können Sie ein Konzept testen oder eine limitierte Auflage starten, ohne sich zu übernehmen." },
    'faq.q2': { en: "What file types do you accept?", zh: "你们接受哪些文件格式？", es: "¿Qué tipos de archivo aceptan?", fr: "Quels types de fichiers acceptez-vous ?", de: "Welche Dateiformate akzeptieren Sie?" },
    'faq.a2': { en: "We accept almost anything — AI, EPS, PDF, PNG, SVG or even a hand-drawn sketch. Our designers will vectorise and refine it for production.", zh: "我们几乎接受任何格式——AI、EPS、PDF、PNG、SVG，甚至手绘草图。我们的设计师会将其矢量化并优化后用于生产。", es: "Aceptamos casi todo: AI, EPS, PDF, PNG, SVG o incluso un boceto a mano. Nuestros diseñadores lo vectorizarán y refinarán para producción.", fr: "Nous acceptons presque tout — AI, EPS, PDF, PNG, SVG ou même un croquis fait main. Nos designers le vectoriseront et l'affineront pour la production.", de: "Wir akzeptieren fast alles — AI, EPS, PDF, PNG, SVG oder sogar eine handgezeichnete Skizze. Unsere Designer vektorisieren und verfeinern es für die Produktion." },
    'faq.q3': { en: "How long does production take?", zh: "生产需要多久？", es: "¿Cuánto tarda la producción?", fr: "Combien de temps dure la production ?", de: "Wie lange dauert die Produktion?" },
    'faq.a3': { en: "Standard production is 7–12 working days after proof approval. Express options are available if you have a tight deadline — just ask.", zh: "标准生产在确认打样后 7–12 个工作日。若交期紧张可申请加急——尽管问。", es: "La producción estándar es de 7–12 días hábiles tras aprobar la muestra. Hay opciones exprés si tienes fecha ajustada; solo pregunta.", fr: "La production standard est de 7–12 jours ouvrés après approbation de l'épreuve. Des options express sont dispo si vous avez un délai serré — demandez.", de: "Die Standardproduktion dauert 7–12 Werktage nach Freigabe des Proofs. Bei knappem Termin gibt es Express-Optionen — fragen Sie einfach." },
    'faq.q4': { en: "Is artwork and proofing really free?", zh: "设计与打样真的免费吗？", es: "¿El arte y la muestra son realmente gratis?", fr: "L'artwork et les épreuves sont-ils vraiment offerts ?", de: "Sind Gestaltung und Proofing wirklich kostenlos?" },
    'faq.a4': { en: "Yes. We create a digital proof and quote at no charge and with no obligation. You only pay once you approve and proceed.", zh: "是的。我们免费制作数字打样与报价，且无需任何义务。您只有在确认并推进后才付费。", es: "Sí. Creamos una muestra digital y un presupuesto sin cargo y sin compromiso. Solo pagas cuando apruebas y avanzas.", fr: "Oui. Nous créons une épreuve numérique et un devis gratuitement et sans engagement. Vous payez seulement après approbation.", de: "Ja. Wir erstellen einen digitalen Proof und ein Angebot kostenlos und unverbindlich. Sie zahlen erst nach Freigabe und Start." },
    'faq.q5': { en: "What's the difference between hard and soft enamel?", zh: "硬珐琅与软珐琅有何区别？", es: "¿Cuál es la diferencia entre esmalte duro y suave?", fr: "Quelle est la différence entre émail dur et tendre ?", de: "Was ist der Unterschied zwischen Hart- und Weichemail?" },
    'faq.a5': { en: "Hard enamel is polished flush with the metal for a smooth, premium finish. Soft enamel has recessed colour with raised metal lines for a textured look and lower cost.", zh: "硬珐琅与金属齐平抛光，呈现顺滑的高级质感。软珐琅色彩凹陷、金属线凸起，质感立体且成本更低。", es: "El esmalte duro se pule a ras del metal para un acabado liso y premium. El suave tiene color recesado con líneas metálicas elevadas, look texturizado y menor costo.", fr: "L'émail dur est poli à fleur de métal pour un fini lisse et premium. L'émail tendre a une couleur encastrée avec lignes métalliques surélevées, look texturé et coût moindre.", de: "Hartemail wird bündig zum Metall poliert für eine glatte, Premium-Oberfläche. Weichemail hat vertiefte Farbe mit erhabenen Metalllinien, strukturiertes Aussehen und geringere Kosten." },
    'faq.q6': { en: "Which plating and attachments can I choose?", zh: "可选哪些镀色与配件？", es: "¿Qué chapado y accesorios puedo elegir?", fr: "Quel placage et quelles fixations puis-je choisir ?", de: "Welche Vergoldung und Befestigungen kann ich wählen?" },
    'faq.a6': { en: "Plating: gold, silver, rose gold, black nickel, antique brass/copper. Attachments: butterfly clutch, rubber clutch, magnetic, screw & cap, or brooch hook.", zh: "镀色：金、银、玫瑰金、黑镍、古铜/古红铜。配件：蝴蝶扣、橡胶扣、磁扣、螺钉帽扣或胸针扣。", es: "Chapado: oro, plata, oro rosa, níquel negro, latón/cobre antiguo. Accesorios: broche mariposa, de goma, magnético, tornillo y tapa, o gancho de broche.", fr: "Placage : or, argent, or rose, nickel noir, laiton/cuivre vieilli. Fixations : papillon, caoutchouc, magnétique, vis et chapeau, ou crochet de broche.", de: "Vergoldung: Gold, Silber, Roségold, Schwarz-Nickel, antik Messing/Kupfer. Befestigungen: Schmetterlingsklemme, Gummiklemme, magnetisch, Schraub- & Kappenverschluss oder Broschenhaken." },
    'faq.q7': { en: "Do you ship internationally?", zh: "你们提供国际配送吗？", es: "¿Envían internacionalmente?", fr: "Expédiez-vous à l'international ?", de: "Versenden Sie international?" },
    'faq.a7': { en: "Yes — tracked shipping to 60+ countries, with customs documentation provided. Delivery times vary by destination.", zh: "是的——可追踪物流送达 60+ 国家，并提供清关文件。送达时间因目的地而异。", es: "Sí, envío rastreado a más de 60 países, con documentos aduaneros. Los tiempos varían según destino.", fr: "Oui — livraison suivie vers 60+ pays, avec documents douaniers fournis. Les délais varient selon destination.", de: "Ja — nachverfolgbarer Versand in über 60 Länder, mit Zollunterlagen. Lieferzeiten variieren je nach Ziel." },
    'faq.q8': { en: "Can I see a sample before the full run?", zh: "大批量前能否先看样？", es: "¿Puedo ver una muestra antes del lote completo?", fr: "Puis-je voir un échantillon avant la série complète ?", de: "Kann ich vor der Serie ein Muster sehen?" },
    'faq.a8': { en: "Absolutely. We can produce a pre-production sample (often at a small fee) so you approve the physical pin before we manufacture the batch.", zh: "当然。我们可制作产前样（通常收少量费用），让您在大批量生产前确认实物徽章。", es: "Por supuesto. Podemos hacer una muestra de preproducción (a menudo con pequeña tarifa) para que apruebes la pin física antes del lote.", fr: "Absolument. Nous pouvons produire un échantillon de préproduction (souvent moyennant un petit frais) pour que vous approuviez l'épingle physique avant la série.", de: "Absolut. Wir können ein Vorproduktionsmuster (oft gegen geringe Gebühr) fertigen, damit Sie die physische Nadel vor der Serie freigeben." },
    'faq.q9': { en: "What if I'm not happy with the result?", zh: "对成品不满意怎么办？", es: "¿Qué pasa si no estoy satisfecho con el resultado?", fr: "Que se passe-t-il si je ne suis pas satisfait du résultat ?", de: "Was, wenn ich mit dem Ergebnis nicht zufrieden bin?" },
    'faq.a9': { en: "Our quality guarantee covers every order. If something isn't right, we'll remake it or refund — no fuss.", zh: "我们的品质保障覆盖每一笔订单。若有问题，我们重做或退款——绝不推诿。", es: "Nuestra garantía de calidad cubre cada pedido. Si algo no está bien, repetimos o reembolsamos sin complicaciones.", fr: "Notre garantie qualité couvre chaque commande. Si quelque chose ne va pas, nous refaisons ou remboursons — sans tracas.", de: "Unsere Qualitätsgarantie deckt jede Bestellung ab. Wenn etwas nicht stimmt, fertigen wir neu oder erstatten — ohne Umstände." },
    'faq.cta': { en: "Contact our team →", zh: "联系我们的团队 →", es: "Contacta a nuestro equipo →", fr: "Contactez notre équipe →", de: "Kontaktieren Sie unser Team →" },
    'contact.eyebrow.hero': { en: "Contact", zh: "联系", es: "Contacto", fr: "Contact", de: "Kontakt" },
    'contact.hero.title': { en: "Get a <span class='hl'>free quote</span>", zh: "获取<span class='hl'>免费报价</span>", es: "Obtén una <span class='hl'>cotización gratis</span>", fr: "Obtenez un <span class='hl'>devis gratuit</span>", de: "Holen Sie sich ein <span class='hl'>kostenloses Angebot</span>" },
    'contact.hero.sub': { en: "Tell us about your project — attach a file if you have one. We'll reply with a design proof and quote within 24 hours. No obligation, ever.", zh: "告诉我们您的项目——如有文件请附上。我们会在 24 小时内回复设计打样与报价。绝不强制，永远。", es: "Cuéntanos de tu proyecto; adjunta un archivo si tienes. Responderemos con una muestra de diseño y cotización en 24 horas. Sin compromiso, nunca.", fr: "Parlez-nous de votre projet — joignez un fichier si vous en avez. Nous répondrons avec épreuve de conception et devis sous 24 h. Sans engagement, jamais.", de: "Erzählen Sie uns von Ihrem Projekt — hängen Sie eine Datei an, falls vorhanden. Wir antworten innerhalb von 24 Stunden mit Design-Proof und Angebot. Unverbindlich, immer." },
    'contact.ok': { en: "Thanks! We've received your request and will reply with a quote within 24 hours.", zh: "谢谢！我们已收到您的请求，将在 24 小时内回复报价。", es: "¡Gracias! Recibimos tu solicitud y responderemos con una cotización en 24 horas.", fr: "Merci ! Nous avons reçu votre demande et répondrons avec un devis sous 24 h.", de: "Danke! Wir haben Ihre Anfrage erhalten und antworten innerhalb von 24 Stunden mit einem Angebot." },
    'contact.lbl.name': { en: "Name *", zh: "姓名 *", es: "Nombre *", fr: "Nom *", de: "Name *" },
    'contact.ph.name': { en: "Your name", zh: "您的姓名", es: "Tu nombre", fr: "Votre nom", de: "Ihr Name" },
    'contact.lbl.email': { en: "Email *", zh: "邮箱 *", es: "Correo *", fr: "E-mail *", de: "E-Mail *" },
    'contact.ph.email': { en: "you@company.com", zh: "您@公司.com", es: "tu@empresa.com", fr: "vous@entreprise.com", de: "sie@firma.de" },
    'contact.lbl.company': { en: "Company / Project", zh: "公司 / 项目", es: "Empresa / Proyecto", fr: "Entreprise / Projet", de: "Firma / Projekt" },
    'contact.ph.optional': { en: "Optional", zh: "选填", es: "Opcional", fr: "Optionnel", de: "Optional" },
    'contact.lbl.phone': { en: "Phone", zh: "电话", es: "Teléfono", fr: "Téléphone", de: "Telefon" },
    'contact.lbl.whatsapp': { en: "WhatsApp", zh: "WhatsApp", es: "WhatsApp", fr: "WhatsApp", de: "WhatsApp" },
    'contact.lbl.country': { en: "Country", zh: "国家", es: "País", fr: "Pays", de: "Land" },
    'contact.ph.country': { en: "e.g. United States", zh: "例如：美国", es: "ej. Estados Unidos", fr: "ex. États-Unis", de: "z. B. Deutschland" },
    'contact.lbl.quantity': { en: "Quantity", zh: "数量", es: "Cantidad", fr: "Quantité", de: "Menge" },
    'contact.ph.quantity': { en: "e.g. 200", zh: "例如：200", es: "ej. 200", fr: "ex. 200", de: "z. B. 200" },
    'contact.lbl.size': { en: "Size", zh: "尺寸", es: "Tamaño", fr: "Taille", de: "Größe" },
    'contact.opt.notsure': { en: "Not sure yet", zh: "暂未确定", es: "Aún no sé", fr: "Pas encore sûr", de: "Noch unsicher" },
    'contact.lbl.message': { en: "Tell us about your pin *", zh: "告诉我们您的徽章需求 *", es: "Cuéntanos de tu pin *", fr: "Parlez-nous de votre épingle *", de: "Erzählen Sie uns von Ihrer Nadel *" },
    'contact.ph.message': { en: "Style, colours, deadline, attachments...", zh: "风格、颜色、截止日期、附件……", es: "Estilo, colores, fecha límite, adjuntos...", fr: "Style, couleurs, délai, pièces jointes...", de: "Stil, Farben, Termin, Anhänge..." },
    'contact.submit': { en: "Send my request →", zh: "提交我的需求 →", es: "Enviar mi solicitud →", fr: "Envoyer ma demande →", de: "Anfrage senden →" },
    'contact.note': { en: "Tip: you can also email <a href='mailto:ycr13120902436@gmail.com'>ycr13120902436@gmail.com</a> with your artwork attached.", zh: "提示：您也可以将设计图发送至 <a href='mailto:ycr13120902436@gmail.com'>ycr13120902436@gmail.com</a>。", es: "Consejo: también puedes enviar tu arte a <a href='mailto:ycr13120902436@gmail.com'>ycr13120902436@gmail.com</a>.", fr: "Astuce : vous pouvez aussi envoyer votre œuvre à <a href='mailto:ycr13120902436@gmail.com'>ycr13120902436@gmail.com</a>.", de: "Tipp: Sie können Ihr Design auch an <a href='mailto:ycr13120902436@gmail.com'>ycr13120902436@gmail.com</a> senden." },
    'contact.info.title': { en: "Reach us directly", zh: "直接联系我们", es: "Contáctanos directamente", fr: "Contactez-nous directement", de: "Erreichen Sie uns direkt" },
    'contact.info.email': { en: "ycr13120902436@gmail.com<br>We reply within 24 hours, Mon–Fri.", zh: "ycr13120902436@gmail.com<br>周一至周五，24 小时内回复。", es: "ycr13120902436@gmail.com<br>Respondemos en 24 horas, lun–vie.", fr: "ycr13120902436@gmail.com<br>Nous répondons sous 24 h, lun–ven.", de: "ycr13120902436@gmail.com<br>Wir antworten innerhalb von 24 Std., Mo–Fr." },
    'contact.info.phone': { en: "+86 13120902436<br>Studio hours 9:00–18:00 GMT", zh: "+86 13120902436<br>工作室时间 9:00–18:00（GMT）", es: "+86 13120902436<br>Horario del estudio 9:00–18:00 GMT", fr: "+86 13120902436<br>Horaires du studio 9h00–18h00 GMT", de: "+86 13120902436<br>Studio-Zeit 9:00–18:00 GMT" },
    'contact.info.addr': { en: "EnamelCraft Studio<br>Guangzhou, Guangdong, China", zh: "EnamelCraft 工作室<br>中国广东广州", es: "Estudio EnamelCraft<br>Guangzhou, Guangdong, China", fr: "Studio EnamelCraft<br>Guangzhou, Guangdong, Chine", de: "EnamelCraft Studio<br>Guangzhou, Guangdong, China" },
    'contact.info.ship': { en: "Worldwide shipping<br>Tracked & insured", zh: "全球配送<br>可追踪且承保", es: "Envío mundial<br>Rastreado y asegurado", fr: "Livraison mondiale<br>Suivie et assurée", de: "Weltweiter Versand<br>Nachverfolgt & versichert" },
    'contact.next.title': { en: "What happens next?", zh: "接下来会发生什么？", es: "¿Qué sigue?", fr: "Que se passe-t-il ensuite ?", de: "Was passiert als Nächstes?" },
    'contact.next.p': { en: "1) We review your brief · 2) Send a free digital proof · 3) You approve · 4) We produce & ship.", zh: "1) 我们审阅需求 · 2) 发送免费数字打样 · 3) 您确认 · 4) 我们生产与发货。", es: "1) Revisamos tu brief · 2) Enviamos muestra digital gratis · 3) Apruebas · 4) Producimos y enviamos.", fr: "1) Nous examinons votre brief · 2) Envoi d'une épreuve numérique gratuite · 3) Vous approuvez · 4) Nous produisons et expédions.", de: "1) Wir prüfen Ihr Briefing · 2) Kostenloser digitaler Proof · 3) Sie geben frei · 4) Wir fertigen & versenden." },
    'prod.hard': { en: "Hard Enamel Pins", zh: "硬珐琅徽章", es: "Pines de Esmalte Duro", fr: "Épingles Émail Dur", de: "Hartemail-Pins" },
    'prod.soft': { en: "Soft Enamel Pins", zh: "软珐琅徽章", es: "Pines de Esmalte Suave", fr: "Épingles Émail Tendre", de: "Weichemail-Pins" },
    'prod.lapel': { en: "Lapel Pins & Brooches", zh: "领针与胸针", es: "Insignias de Solapa y Broches", fr: "Insignes et Broches", de: "Anstecknadeln & Broschen" },
    'prod.badge': { en: "Custom Badges", zh: "定制徽章", es: "Insignias Personalizadas", fr: "Badges Personnalisés", de: "Individuelle Abzeichen" },
    'foot.tagline': { en: "Custom enamel pins, badges & brooches manufactured to your design. Low minimums, free artwork, worldwide delivery.", zh: "按您的设计定制珐琅徽章、胸针与奖牌。低起订量、免费设计、全球发货。", es: "Pines, insignias y broches de esmalte fabricados a tu diseño. Pedidos mínimos bajos, arte gratis, envío mundial.", fr: "Épingles, badges et broches en émail fabriqués selon votre design. Petites quantités, artwork offert, livraison mondiale.", de: "Individuelle Emailleschilder, Abzeichen & Broschen nach Ihrem Design. Niedrige Mindestmengen, kostenlose Gestaltung, weltweiter Versand." },
    'foot.col.products': { en: "Products", zh: "产品", es: "Productos", fr: "Produits", de: "Produkte" },
    'foot.col.company': { en: "Company", zh: "公司", es: "Empresa", fr: "Entreprise", de: "Unternehmen" },
    'foot.col.support': { en: "Support", zh: "支持", es: "Soporte", fr: "Support", de: "Support" },
    'foot.about': { en: "About Us", zh: "关于我们", es: "Sobre Nosotros", fr: "À propos", de: "Über Uns" },
    'foot.work': { en: "Our Work", zh: "我们的作品", es: "Nuestro Trabajo", fr: "Nos Réalisations", de: "Unsere Arbeiten" },
    'foot.rights': { en: "All rights reserved.", zh: "保留所有权利。", es: "Todos los derechos reservados.", fr: "Tous droits réservés.", de: "Alle Rechte vorbehalten." },
    'foot.made': { en: "Crafted with care · Placeholder brand — rename freely", zh: "用心打造 · 占位品牌——可自由改名", es: "Hecho con cuidado · Marca de ejemplo — renómbrala libremente", fr: "Fabriqué avec soin · Marque fictive — renommez librement", de: "Mit Sorgfalt gefertigt · Platzhalter-Marke — frei umbenennbar" },
  };

  var STORE_KEY = 'ec_lang';
  var DEFAULT = 'en';
  var box = null;

  function isValid(l) { return LANG_CODES.indexOf(l) !== -1; }
  function getLang() {
    var l = localStorage.getItem(STORE_KEY);
    return isValid(l) ? l : DEFAULT;
  }
  // value with English fallback so missing keys never blank out
  function val(key, lang) {
    var e = DICT[key];
    if (!e) return '';
    return e[lang] || e['en'] || '';
  }

  function apply(lang) {
    document.querySelectorAll('[data-i18n],[data-i18n-html],[data-i18n-attr]').forEach(function (el) {
      var key = el.getAttribute('data-i18n') || el.getAttribute('data-i18n-html') || el.getAttribute('data-i18n-attr');
      var v = val(key, lang);
      if (!v) return;
      if (el.hasAttribute('data-i18n-html')) el.innerHTML = v;
      else if (el.hasAttribute('data-i18n-attr')) el.setAttribute(el.getAttribute('data-i18n-attr'), v);
      else el.textContent = v;
    });
    // fallback for pages that haven't marked title/meta with data-i18n yet
    var meta = document.querySelector('meta[name="description"]');
    if (meta && !meta.hasAttribute('data-i18n-attr')) meta.setAttribute('content', val('meta.desc', lang));
    var t = val('meta.title', lang);
    if (document.querySelector('title') && !document.querySelector('title').hasAttribute('data-i18n')) {
      if (t) document.title = t;
    }
    document.documentElement.lang = HTML_LANG[lang] || lang;
    updateToggle(lang);
  }

  function setLang(lang) {
    if (!isValid(lang)) return;
    localStorage.setItem(STORE_KEY, lang);
    apply(lang);
  }

  function updateToggle(lang) {
    if (!box) return;
    var cur = box.querySelector('.lang-current');
    if (cur) cur.textContent = (LANG_MAP[lang] ? LANG_MAP[lang].code : lang).toUpperCase();
    box.querySelectorAll('.lang-menu li').forEach(function (li) {
      li.classList.toggle('active', li.getAttribute('data-lang') === lang);
    });
  }

  function buildDropdown() {
    box = document.getElementById('langDropdown');
    if (!box) return;
    var cur = getLang();
    var menu = LANGS.map(function (x) {
      return '<li role="menuitem" data-lang="' + x.code + '"><span class="ln">' + x.name +
             '</span><span class="lc">' + x.code.toUpperCase() + '</span></li>';
    }).join('');
    box.innerHTML =
      '<button type="button" class="lang-toggle" aria-haspopup="true" aria-expanded="false">' +
        '<span class="lang-current">' + (LANG_MAP[cur] ? LANG_MAP[cur].code : cur).toUpperCase() + '</span>' +
        '<svg class="chev" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polyline points="6 9 12 15 18 9"/></svg>' +
      '</button>' +
      '<ul class="lang-menu" role="menu">' + menu + '</ul>';

    var toggle = box.querySelector('.lang-toggle');
    toggle.addEventListener('click', function (e) {
      e.stopPropagation();
      var open = box.classList.toggle('open');
      toggle.setAttribute('aria-expanded', open ? 'true' : 'false');
    });
    box.querySelectorAll('.lang-menu li').forEach(function (li) {
      li.addEventListener('click', function () {
        setLang(li.getAttribute('data-lang'));
        box.classList.remove('open');
        toggle.setAttribute('aria-expanded', 'false');
      });
    });
  }

  function closeOutside(e) {
    if (box && box.classList.contains('open') && !box.contains(e.target)) {
      box.classList.remove('open');
      var t = box.querySelector('.lang-toggle');
      if (t) t.setAttribute('aria-expanded', 'false');
    }
  }

  document.addEventListener('DOMContentLoaded', function () {
    buildDropdown();
    document.addEventListener('click', closeOutside);
    apply(getLang());
  });

  // helper for other scripts (e.g. site.js floating CTA)
  window.__i18n = {
    t: function (key) { return val(key, getLang()); },
    set: setLang,
    get: getLang
  };
})();
